# Generated by Django 3.2 on 2021-05-12 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_auto_20210510_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='categories',
            name='subscribers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
