# Generated by Django 3.2 on 2021-05-20 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0009_auto_20210520_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='categories',
            name='subscribers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
